---
- name: インストール
  yum:
    name={{ item }}
    state=present
  with_items:
    - mail
    - postfix
  tags:
    - postfix

- name: ユーザにサブグループを追加
  user:
    name={{ user }}
    groups=mail
    append=yes
  tags:
    - postfix

- name: aliases.regexp配置
  copy:
    src=aliases.regexp
    dest=/etc/aliases.regexp
    mode=644
    backup=yes
  tags:
    - postfix

- name: main.cf alias_maps, inet_interfacesを修正
  replace:
    dest=/etc/postfix/main.cf
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - {
        regexp:  '^alias_maps = hash:/etc/aliases$',
        replace: 'alias_maps = hash:/etc/aliases, pcre:/etc/aliases.regexp'
      }
    - {
        regexp:  '^inet_protocols = all$',
        replace: 'inet_protocols = ipv4'
      }
  tags:
    - postfix

- name: transport_maps配置
  copy:
    src=transport_maps
    dest=/etc/postfix/transport_maps
    mode=644
    backup=yes
  tags:
    - postfix

- name: transport_mapsを設定に追記
  lineinfile:
    dest=/etc/postfix/main.cf
    state=present
    line='transport_maps = pcre:/etc/postfix/transport_maps'
  tags:
    - postfix

- name: サービス登録・起動
  service:
    name=postfix
    state=started
    enabled=yes
  notify:
    - restart-postfix
  tags:
    - postfix
