---
- name: インストール
  yum:
    name={{ item }}
    state=present
  with_items:
    - dovecot
  tags:
    - dovecot

- name: dovecot.conf protocols修正
  replace:
    dest=/etc/dovecot/dovecot.conf
    regexp='^#protocols = imap pop3 lmtp$'
    replace='protocols = imap'
  notify:
    - restart-dovecot
  tags:
    - dovecot

- name: 10-auth.conf auth修正
  replace:
    dest=/etc/dovecot/conf.d/10-auth.conf
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - {
        regexp:  '^#disable_plaintext_auth = yes$',
        replace: 'disable_plaintext_auth = no'
      }
    - {
        regexp:  '^auth_mechanisms = plain$',
        replace: '#auth_mechanisms = plain'
      }
  notify:
    - restart-dovecot
  tags:
    - dovecot

- name: 10-mail.conf mail_location修正
  replace:
    dest=/etc/dovecot/conf.d/10-mail.conf
    regexp='^#mail_location = $'
    replace='mail_location = mbox:~/mail:INBOX=/var/mail/%u'
  notify:
    - restart-dovecot
  tags:
    - dovecot

- name: 受信ディレクトリ作成
  file:
    state=directory
    path=/home/{{ user }}/mail/.imap/INBOX
    owner={{ user }}
    group={{ user }}
  tags:
    - dovecot

- name: サービス登録・起動
  service:
    name=dovecot
    state=started
    enabled=yes
  notify:
    - restart-dovecot
  tags:
    - dovecot
