---
- name: インストール
  yum:
    name=phpMyAdmin
    enablerepo=remi,remi-php55
    state=present
  tags:
    - phpmyadmin

- name: ホストからアクセスできるよう強制修正
  replace:
    dest=/etc/httpd/conf.d/phpMyAdmin.conf
    regexp='^     Allow from 127.0.0.1'
    replace='     Allow from All'
  notify:
    - restart-httpd
  tags:
    - phpmyadmin
